# Generated by Django 4.2.7 on 2023-12-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsTalk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='question3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='useranswers',
            name='question8',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question2',
            field=models.TextField(default=''),
        ),
    ]
