# Generated by Django 4.2.7 on 2023-12-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LetsTalk', '0002_useranswers_question3_useranswers_question4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='question1',
            field=models.TextField(default='', verbose_name='How would you describe our relationship and What do you think makes our bond unique?'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question2',
            field=models.TextField(default='', verbose_name='What is your favorite memory of us together?'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question3',
            field=models.TextField(default='', verbose_name='Are there aspects of my life or feelings that you think I may not openly express?'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question4',
            field=models.TextField(default='', verbose_name='What advice would you offer me when navigating tough times?'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question5',
            field=models.TextField(default='', verbose_name="How close am I to you so that you'll share everything with me?"),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question6',
            field=models.TextField(default='', verbose_name='Are you proud of me?'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question7',
            field=models.TextField(default='', verbose_name='Are there any changes you think I could make to improve or enhance myself?'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='question8',
            field=models.TextField(default='', verbose_name='Any suggestions for me?'),
        ),
    ]
